internal import AppKit
import Foundation

@MainActor
final class SystemClipboardMonitor: ClipboardMonitoring {
    static let maximumTextBytes = 512 * 1_024
    static let maximumImageBytes = 8 * 1_024 * 1_024
    static let maximumFileCount = 100

    var onClipboardChange: ((ClipboardSnapshot) -> Void)?

    private let pasteboard: NSPasteboard
    private let pollingInterval: TimeInterval
    private var timer: Timer?
    private var lastChangeCount: Int

    init(
        pasteboard: NSPasteboard = .general,
        pollingInterval: TimeInterval = 0.1
    ) {
        self.pasteboard = pasteboard
        self.pollingInterval = pollingInterval
        self.lastChangeCount = pasteboard.changeCount
    }

    deinit {
        timer?.invalidate()
    }

    func startMonitoring() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount

        let timer = Timer(timeInterval: pollingInterval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.checkPasteboard()
            }
        }
        self.timer = timer
        RunLoop.main.add(timer, forMode: .common)
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
        lastChangeCount = pasteboard.changeCount
    }

    func write(_ payload: ClipboardPayload) -> Bool {
        pasteboard.clearContents()

        let didWrite: Bool
        switch payload {
        case .text(let text):
            didWrite = pasteboard.setString(text, forType: .string)

        case .files(let urls):
            didWrite = pasteboard.writeObjects(urls.map { $0 as NSURL })

        case .image(let data):
            guard let image = NSImage(data: data) else {
                lastChangeCount = pasteboard.changeCount
                return false
            }
            didWrite = pasteboard.writeObjects([image])
        }

        // Restoring an older item is an app-owned write, not a new history item.
        lastChangeCount = pasteboard.changeCount
        return didWrite
    }

    static func shouldIgnore(types: [NSPasteboard.PasteboardType]) -> Bool {
        let identifiers = types.map { $0.rawValue.lowercased() }
        return identifiers.contains { identifier in
            ignoredTypeIdentifiers.contains(identifier) ||
            identifier.contains("concealed") ||
            identifier.contains("transient") ||
            identifier.contains("password")
        }
    }

    private func checkPasteboard() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        let types = pasteboard.types ?? []
        guard !Self.shouldIgnore(types: types),
              let payload = readPayload() else {
            return
        }

        let sourceName = NSWorkspace.shared.frontmostApplication?.localizedName
        onClipboardChange?(
            ClipboardSnapshot(
                payload: payload,
                sourceApplicationName: sourceName,
                capturedAt: .now
            )
        )
    }

    private func readPayload() -> ClipboardPayload? {
        let fileOptions: [NSPasteboard.ReadingOptionKey: Any] = [
            .urlReadingFileURLsOnly: true
        ]
        if let objects = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: fileOptions
        ) as? [NSURL] {
            let urls = objects.map { $0 as URL }
            if !urls.isEmpty {
                return Self.filePayload(from: urls)
            }
        }

        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
           !data.isEmpty,
           data.count <= Self.maximumImageBytes,
           NSImage(data: data) != nil {
            return .image(data)
        }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
           text.utf8.count <= Self.maximumTextBytes {
            return .text(text)
        }

        return nil
    }

    static func filePayload(from urls: [URL]) -> ClipboardPayload? {
        guard !urls.isEmpty, urls.count <= maximumFileCount else { return nil }
        return .files(urls)
    }

    private static let ignoredTypeIdentifiers: Set<String> = [
        "org.nspasteboard.transienttype",
        "org.nspasteboard.concealedtype",
        "org.nspasteboard.autogeneratedtype",
        "com.agilebits.onepassword",
        "com.1password.password"
    ]
}
